### ISSUE TITLE
Thank/like post to show post content - add a hook for other plugins

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#172]
This is one of the most requested feature by users who wrote me PMs.

I am not sure if it is something easy to add or if we will add this feature. Anyway lets discuss :) 

It should work in that way - thread author (or maybe post author too) can select option to hide content until user will add thank/like to the post. After that the content is displayed via AJAX. 

**There is my concept for setting in ACP:**
- only the first post/all
- select forums where enable
- select usergroups who can use this feature
- select usergroups who can see hidden post content without adding thanks/likes (moderators, admins, etc)

For hiding content we can use mycode tag - author can select which part of post will be hidden, or add a setting (check field) into the post (full reply) to hide the whole content (I dont like this way).

**Comment by lairdshaw** [comment]
What sort of situations do you imagine this feature being used in, @Eldenroot (and anybody else who wants to answer)?

**Comment by Eldenroot** [comment]
@lairdshaw - we have a lot of requests on this feature from users. This feature can be added to MyBB via "premium" plugin nowadays, but ...

My opinion: a lot of users do not use thank/like buttons, just write "Thank you" or nothing (thats bad altitude). So with this feature we can  enhance our plugin a lot. Lets say: author created a new thread with something really useful (manual, tips, review, etc). Author can set if the post will be displayed without any restriction to everyone (so no thanks/likes is needed to display a content). OR author can choose "User must add thank/like to post to display the content". So visitor will see only a placeholder with information about that, add thank/like to post to see the content. After that the content will be displayed for that user. 

We can discuss how it should work and what settings it will need. We can also add (lets say if it would be easy to add) that visitors must add set thanks/likes count to post to display the content (but seems to be quite tricky and it could have a negative feedback on small forums). 

What do you think?

**Comment by lairdshaw** [comment]
> What do you think?

I guess I'm a little puzzled. To my mind, the purpose of adding a thanks/like to a post is to express your appreciation for its content, so I'm struggling to see the sense in thanking/liking a post whose content you haven't yet seen.

It seems your idea is to make sure that good content is rewarded, which is a good idea, but I'm not sure how rewarding it is to know that people only "liked" your content because they wanted to see it, and not necessarily because, after seeing it, they actually thought it *was* any good.

I guess I see it as a different use-case than the standard thanks/likes of this plugin. Adding a new type might be a better idea than reusing the standard thanks/likes (maybe something like "intrigues", as in, "I am intrigued to see this content"), but also might be way over-complicating the plugin.

**Comment by Eldenroot** [comment]
OK, I see you point. Thats why I opened the issue to discuss and know your opinions.

If we would work on this in future, I would stick to the most simplest solution which will use mycode tags to hide specific part of the post. I edited my previous post just at the same time you posted yours one.

**Comment by lairdshaw** [comment]
> Thats why I opened the issue to discuss and know your opinions.

Hopefully others will offer their opinions too. By the way, just to be sure I understand: this feature request can't be satisfied by a simple "spoiler" plugin, right? Folks are wanting not just to hide spoilers, but to be tyled when the "spoiler" is revealed, correct?

**Comment by Eldenroot** [comment]
> Folks are wanting not just to hide spoilers, but to be tyled when the "spoiler" is revealed, correct?

Yes, they want to hide content and only if user will add thank/like to the post the content will be displayed (AJAX).

**Comment by 8guawong** [comment]
this feature is usually used in sharing forums
where instead having users reply to see hidden content they can use thanks to show the hidden content
this prevents useless posts like "thanks for sharing" 
also i'm not sure if this thanks plugin could be used this way but you can also use it to promote users to different groups based on number of thanks they received ;-)

**Comment by Eldenroot** [comment]
@lairdshaw I was thinking about this one today, I think we can close it and not to add. This is a really most wanted feature by users BUT ai am not sure if it fita into this plugin... So what do you think, can we close?

Maybe there could be an extra plugin for that on top of thank you like if anybody would like to add...

**Comment by lairdshaw** [comment]
@Eldenroot, for the reason I explained above, this feature does not make sense to me personally, and I have no personal use for it, so I am not motivated to implement it. That said, "it's not all about me": if it is a high-demand feature, then it makes sense to satisfy that demand. So, if you can find somebody else to implement it, or if you implement it yourself, then that seems reasonable. Re your idea of an extra plugin which separately implements it, that could work too, although we'd need to implement at least one hook into our plugin to facilitate that - a `tyl_like_added` hook or something like that so the extra plugin knows when it can reveal content.

So, thank you for asking for my opinion, but I think in the light of all of that, the decision is entirely yours to make. I have no problem with whatever you decide!

**Comment by Eldenroot** [comment]
We are a team, so your opinion is welcome :) Thank you for your reply!

Extra hook would be enough.

**Comment by lairdshaw** [comment]
A hook into the end of the Javascript function `addDone` in our thankyoulike.js script would probably be best. I assume that the new plugin would use that hook to make a call to the server to pull out the hidden content and display it in the post without the need for a page reload.

**Comment by Eldenroot** [comment]
Yeah I agree with you. This is the how it should work. Can I ask you to just add a hook, but not for 3.3.7, we should postpone this to 3.3.8 or later.

**Comment by Eldenroot** [comment]
@lairdshaw - please can you add a hook into the JS file? Thank you!

**Comment by lairdshaw** [comment]
Yessir. See what you think of this.

**Comment by Eldenroot** [comment]
Thank you, great!
