### ISSUE TITLE
Add support for NewPoints plugin

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#173]

**Comment by Eldenroot** [comment]
I do not use this plugin anymore, quite difficult to maintain support for 3rd party plugins, we should close this up.

@lairdshaw

**Comment by lairdshaw** [comment]
I accept your decision on this, mostly because I'm not very familiar with NewPoints. It does seem to be a popular plugin though, so maybe we can reconsider down the track.
