### ISSUE TITLE
Clean up tylsearch.php

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#183]
I think this file will need some love in future - missing comments, formatting of code etc.

**Comment by Eldenroot** [comment]
@lairdshaw - is there any way to clean up or optimise this php file? Can you look at this if you will have some spare time not being in a warfare vs your kitchen and dishes? :)

**Comment by effone** [comment]
Don't know what you want here, but the file looks fine at a glance to me.

**Comment by Eldenroot** [comment]
If it is fine let it be :)

**Comment by lairdshaw** [comment]
Yep, my reaction was the same as @effone's - sorry for not expressing it right away.
