### ISSUE TITLE
Display users from thanks/like list in modal/new page

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#185]
This is open for discussion - I received PM from a user yesterday on MyBB board. 

> _The request - is possible to add support to display users and the time/date when the post was thanked/liked in a modal or in a new page? I needs this for my board to follow my design._

My opinion:
I prefer a modal popup window, but it seems to be quite tricky in posts with a lot of thanks/likes. The popup will be huge. 

And off-topic:
I agree that the UI (graphical) looks of the thanks/like list under the post needs some love to be nice in 21st century, I can redesign it, it is only a CSS code, but not sure how it should look like.

**Comment by lairdshaw** [comment]
> I prefer a modal popup window, but it seems to be quite tricky in posts with a lot of thanks/likes. The popup will be huge.

Maybe it could have a fixed maximum height of less than the window height, and automatic vertical scroll bars if it overflows?

Both possibilities - modal popup and new page - could be implemented, allowing admins to choose which they prefer (including fallback to full page if Javascript isn't enabled for the popup).

**Comment by Eldenroot** [comment]
Ok, do you have some ideas?

**Comment by lairdshaw** [comment]
No - that's what I was trying to say, that I wish I had ideas for you but I don't because design's not my strength. We miscommunicated... oh well, it happens. :-)
