### ISSUE TITLE
FontAwesome - use icons in buttons, list etc - tutorial

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#191]
I will create a short but useful tutorial for our users. Many of them do not know how to replace icons by FontAwesome icons etc. I will create this tutorial during my holidays, I hope that I will find enough free time next week. I hope that this tutorial will reduce the amount of support PMs and emails from these users and help them to customize our plugin for they needs.

**Comment by lairdshaw** [comment]
A good and useful idea.
