### ISSUE TITLE
New option - show full/simple navigation for member profile box (top rated post)

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#192]
This is an improvement for member profile box with top thanked/liked user's post.

Now it display only "FORUM" where the post is located, would be nice to add an option to choose between full navigation path - lets say:

>  Discussion » Plugins » Development 

and the "simple" mode (which we have now), so the output will be:

> "Development"

The new field for the symbol displayed in navigation will be required - we can use lang string or new field in ACP option page. Or we can use hardcoded "»".

Discussion, Plugins, Development should be clickable links.

Lets discuss :)

**Comment by Eldenroot** [comment]
@lairdshaw - can we close this one?

**Comment by lairdshaw** [comment]
I still think it's a good idea. I had just lost track of it. I think it would also be nice to add the date of the post.

**Comment by Eldenroot** [comment]
Wow, nice idea, I will open a new ticket for it :)
