### ISSUE TITLE
Extend displaying of total thx/likes in the first post for search page 

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#215]
#214 but for search.php page

**Comment by Eldenroot** [comment]
@lairdshaw - I am thinking about this one to, not for 3.3.7 but for the 3.3.8. I will create a PR after 3.3.7 release. 

I think it should be almost same as I did for forumdisplay.php, can I ask you to check my PR when will be ready (in 2-3 weeks)? Thank you!

**Comment by lairdshaw** [comment]
> can I ask you to check my PR when will be ready (in 2-3 weeks)?

Sure - just let me know when it's ready.
