### ISSUE TITLE
Button Code Wrapping

### ISSUE THREAD

**Issue by effone** [mybbgroup/Thank-you-like-system#219]
Button code using `div` resulting the postbit button series breaking into 2 lines.

![snap](https://i.ibb.co/s15JRPs/screen.gif)

https://community.mybb.com/thread-224696.html

**Comment by Eldenroot** [comment]
@effone - you are right, I created a PR, please can you review it? :) thx!

**Comment by effone** [comment]
I'll leave it for now to test with some themes.
This happens only with custom themes it seems.

**Comment by Eldenroot** [comment]
First of all we need to make it fully compatible with MyBB default theme... custom themes are not fully supported out of the box.

**Comment by effone** [comment]
MyBB's default postbit button framing is `a` link, neither `div` nor `span`. So our button code is already odd.
I suggested to use span for a quick fix, but if you follow MyBB core code it should be an a link only.
