### ISSUE TITLE
Hide Unwanted Links

### ISSUE THREAD

**Issue by effone** [mybbgroup/Thank-you-like-system#228]
Inline with the recent [cleanup improvements in MyBB Core](https://github.com/mybb/mybb/issues/3540) omit the "Find All ...." threads / posts links in profile if there is no likes / thanks given / received.

**Comment by Eldenroot** [comment]
I agree, good point

**Comment by Eldenroot** [comment]
@lairdshaw - is it doable with small code changes or should we postpone this into 3.3.8 or later?

**Comment by lairdshaw** [comment]
See what you think. ;-)

**Comment by Eldenroot** [comment]
Added by @lairdshaw , thank you!
