### ISSUE TITLE
Reputation not added in some cases

### ISSUE THREAD

**Issue by panayotb** [mybbgroup/Thank-you-like-system#229]
In some cases (for example from Tapatalk) when a thank is given, reputation points are not added. I found that the problem is in thankyoulike.php

Reputation points are given on line 280:
https://github.com/mybbgroup/Thank-you-like-system/blob/master/thankyoulike.php#L280

But this line is unreachable because of the code above the reputation block (when execution goes to the "else" statement:

```php
if($mybb->input['ajax'])
{
	// Do nothing here
}
else
{
	// Go back to the post
	$url = get_post_link($pid, $tid)."#pid{$pid}";
	redirect($url, $lang->sprintf($lang->tyl_redirect_tyled, $pre).$lang->tyl_redirect_back);
	exit;
}
```
Above code needs to be after reputation block.

Same thing happens when deleting reputation.

If you wonder how tapatalk gets to the else statement, it does the following:

```php
$_GET['action'] = 'add';
include('thankyoulike.php');
```

**Comment by SvePu** [comment]
We should include the redirects after all db actions

**Comment by SvePu** [comment]
@Eldenroot : Pls test changes

**Comment by Eldenroot** [comment]
@SvePu - do you plan to add anything else to this fix? Or to anything else reported here in GitHub issues list?
