### ISSUE TITLE
Prevent templates unchanged between plugin versions from showing in Find Updated Templates

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#232]
We recently fixed a bug - #230 - with template versioning. There is still a (more minor) problem though: plugin templates customised by the user will still show up in Find Update Templates after plugin upgrade even if the plugin doesn't make any changes to those templates. It seems to me that in this scenario, they should not show up in Find Updated Templates if they weren't showing up prior to plugin upgrade.

The way to fix this is, I think, to amend the $tyl_templates array in tyl_insert_templates() so that each entry stores not just the template's code, but also the version of the plugin at the time the template was last updated. Then, when inserting templates just below that, we would only set to zero the version of customised plugin templates (which makes them show up in Find Updated Templates) if the installed version of the plugin from which we are upgrading is less than the version at which the template in question was last modified.

The only drawbacks I can see to this approach are that:

1. To do it properly (that is, to determine for each template the exact version number at which it was last changed) would take a bit of effort and digging around in git.
2. It requires us to remember to update the last-modded version number for a template if/when we change it, which gets messy when the next release's version number has not yet been determined (i.e., which component of the version numbering it will increment).

Thoughts?

**Comment by Eldenroot** [comment]
We use about 10 templates in total, not more... 

So you suggest to use "MyBB versioning" for templates? If we have only 10 templates it should not be a problem (may of them were not updated for ages).

**Comment by lairdshaw** [comment]
> So you suggest to use "MyBB versioning" for templates?

Yes, kind of - in the sense that MyBB core code associates version numbers with its templates to achieve the same outcome I'm suggesting we aim for: after upgrade, *even if* a template has been customised by the user, don't show it in Find Updated Templates if (1) it wasn't already showing in there before the upgrade, AND (2) it wasn't updated BY the upgrade.

But also, kind of not - in the sense that we would use plugin version numbers rather than core code version numbers to achieve this.

> If we have only 10 templates it should not be a problem (may of them were not updated for ages).

Yes, it shouldn't be an excessive amount of work.

**Comment by Eldenroot** [comment]
I agree with you! Good solution!

**Comment by Eldenroot** [comment]
@lairdshaw - can I ask you if you will have some time and wou will be back from travels to take a look? Thx!

**Comment by lairdshaw** [comment]
Ah, apologies, @Eldenroot: I am currently working on something else (which I'll share with you privately in due course), and still on my backup netbook as my main laptop has not yet come back from repairs, but I will try to get this done at some point in the not-too-distant future.

**Comment by lairdshaw** [comment]
Nevermind, I took the time to implement this without delay. See my pull request.

**Comment by Eldenroot** [comment]
@lairdshaw - thank you buddy for your time and contribution!
