### ISSUE TITLE
Use versioning for JS files

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#233]
Just one idea - what about to use version number in JS files which are loaded in templates? It would avoid issues with "cached" JS during updates.

@lairdshaw

**Comment by lairdshaw** [comment]
It's a very good idea. I like it.

**Comment by Eldenroot** [comment]
What would be the best way to do apply this? Manually add ?ver=XXX where XXX will be the version number of plugin into the js url in template (MyBB way?)?

**Comment by lairdshaw** [comment]
Yes, that seems best. And remember to update the new 'version_at_last_change' property of the templates you change to the version of the next upcoming release.

**Comment by Eldenroot** [comment]
Added via https://github.com/mybbgroup/Thank-you-like-system/pull/236
