### ISSUE TITLE
Browser console - JS error

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#234]
![image](https://user-images.githubusercontent.com/778890/76681688-e9ac5680-65f5-11ea-9a09-8e35f97c9edd.png)

**Comment by lairdshaw** [comment]
Steps to reproduce? Can't reproduce it here.

**Comment by lairdshaw** [comment]
My guess is that you have made independent modifications to the "showthread" template, and that somehow in the confusion of all of the mods to that template, the new addition to that template that my recent commit to this plugin makes got lost. That addition, to be clear, is the line:

`	var tylCollDefault = "{$mybb->settings[\'g33k_thankyoulike_colldefault\']}";`

which appears in [line 964 of inc/plugins/thankyoulike.php](https://github.com/mybbgroup/Thank-you-like-system/blob/fc406092dd95f8b5b14fc65e18c972521af72c29/inc/plugins/thankyoulike.php#L964).

Can you please check whether that line appears in your "showthread" template, and, if not, then let us know whether the problem disappears when you add it?

**Comment by lairdshaw** [comment]
P.S. If you copy it from the above, then be sure to get rid of the two backslashes - which each appear before a single quote - before adding it to the template.

**Comment by Eldenroot** [comment]
@lairdshaw - you are right, now it is solved! Thx!
