### ISSUE TITLE
tylCollDefault is not defined

### ISSUE THREAD

**Issue by effone** [mybbgroup/Thank-you-like-system#239]
>Uncaught ReferenceError: tylCollDefault is not defined

This is meant to carry the default setting value of the like list to determine its collapse state, but not defined in final output, resulting all the like lists remain expanded.

![snap](https://i.imgur.com/8Oudpqf.png)

**Comment by lairdshaw** [comment]
I can't reproduce this - can you please provide steps to replicate, @effone?

**Comment by effone** [comment]
I am getting this in console of every showthread.
This should be declared in this chunk, But I can't see there as well...

```
<script type="text/javascript">
 <!--
    var tylEnabled = "1";
    var tylDisplayGrowl = "1";
    var tylCollapsible = "1";
    var tylUser = "0";
    var tylSend = "Added Like to this post";
    var tylRemove = "Removed Like from this post";
// -->
</script>
```
You can experience this at https://mybb.group, visit any thread and open console. (note, jQuery is updated to 3.5.1)

Can you also confirm that if you collapse a thank list of a particular post, the state is remembered after page refresh?

**Comment by lairdshaw** [comment]
> This should be declared in this chunk, But I can't see there as well...

It looks like it's there to me, on [line 1019](https://github.com/mybbgroup/Thank-you-like-system/blob/1e1cc83401f2a81967f6e3dfeb771e155af27cf6/inc/plugins/thankyoulike.php#L1019).

> You can experience this at https://mybb.group, visit any thread and open console. (note, jQuery is updated to 3.5.1)

Are you sure the plugin has been updated to the latest version (3.3.6) on that forum?

> Can you also confirm that if you collapse a thank list of a particular post, the state is remembered after page refresh?

Yes. Confirmed.

**Comment by effone** [comment]
Nope, its `3.2.0`. I'll update and revert.

**Comment by Eldenroot** [comment]
@effone - result? I think it is fine on latest version but I would like to know your observation :)

**Comment by effone** [comment]
Updated. But I am still getting the same error in console. Happening with all the themes.
@Eldenroot you can check this out at group site.

I'll also manage time to check in deep.

**Comment by lairdshaw** [comment]
It looks like the templates haven't been updated properly via the `find_replace_templatesets()` calls in `thankyoulike_activate()`. Did you follow the upgrade procedure of deactivate-copyfiles-reactivate? (Order is important). What happens now if you deactivate and then reactivate? (Be warned that you might need to fix up some templates if you do that).

**Comment by effone** [comment]
> Be warned that you might need to fix up some templates if you do that
That. That will break my entire layout.
I'll read the plugin code and alter template manually. Thanks.
Once it gets resolved I will close this issue.

**Comment by Eldenroot** [comment]
I cannot reproduce, no console error with latest version...
