### ISSUE TITLE
Display user avatars instead of links

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#240]
Really cool idea:
https://community.mybb.com/thread-169382-post-1356406.html#pid1356406 and below

**Comment by lairdshaw** [comment]
Yep, a very cool idea. Have assigned myself. Also, perhaps you would like to add an issue for this idea which I'll also assign to myself:

https://community.mybb.com/thread-169382-post-1353337.html#pid1353337

**Comment by Eldenroot** [comment]
Thank you very much, I will open a new issue ASAP. Other ideas and improvements are welcome! :)

**Comment by Eldenroot** [comment]
Added, thx @lairdshaw
