### ISSUE TITLE
Make a possibility to use coloration for amount of thx/likes like MyBB rep system

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#242]
https://community.mybb.com/thread-169382-post-1353337.html#pid1353337

@lairdshaw 

This has a great potential - we can add (in future if it is too complicated) some system for different colors of text based on number of likes/thx. Lets say:
- 0 = grey
- 1-10 = yellow
- 10-50 = orange
- 51-150 = green

etc. - is that doable alongside with some CSS magic?

**Comment by Eldenroot** [comment]
Maybe make this "number" clickable to redirect into list of likes/thanks? I am not sure... I really like how MyBB uses this kind of table:

https://community.mybb.com/reputation.php?uid=116662

![image](https://user-images.githubusercontent.com/778890/94561703-a8fbee00-0264-11eb-88b5-0d4561aa7818.png)

**Comment by lairdshaw** [comment]
Now you're thinking big. I like it. Yes, it's all doable, and not especially difficult, it just requires knuckling down and getting it done.

**Comment by Eldenroot** [comment]
I will open a separate issue for the thx/likes page. Thx!
