### ISSUE TITLE
Display date/time for top liked/thx post 

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#248]
As title says - add more info for this feature

https://github.com/mybbgroup/Thank-you-like-system/issues/192#issuecomment-703244148

**Comment by Eldenroot** [comment]
@lairdshaw - maybe this would be the last feature for the next release?  I have been testing new features, so far so good.

Or do you plan anything else, what do you think? Maybe with this addition we can redesign the layout a lottle bit, not sure.

**Comment by lairdshaw** [comment]
@Eldenroot! I have been a little distracted, but yes, I think we could implement this feature before the next release. Let me know of any ideas you have for a redesigned layout and I'll try to code them for you.

**Comment by Eldenroot** [comment]
@lairdshaw - no problem 👍 
I am quite not satisfied with the current layout
![image](https://user-images.githubusercontent.com/778890/95365271-34632800-08d2-11eb-8d22-272f659ab301.png)

It needs a little bit of love, maybe do we need post and thread subject? I know that in 99,99 % of cases it is same but maybe some users may use it... anyway, we can add time/date next to the counter of thx/likes.

**Comment by Eldenroot** [comment]
Moreover we should display thread prefix and maybe also think about "Read more" for shortened post content with redirection to the post itself.

Maybe same for the counter, make it clickable or use same color if you set the levels (coloration) - #242

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/95366684-0da5f100-08d4-11eb-8687-54aef8af3f6d.png)
 maybe first idea :) needs to be improved and think about the others info placement.

**Comment by lairdshaw** [comment]
Gotta catch some ZZZs, my man, and then I'll check back in here and we can get this sorted, possibly after I've done a little more work on the bugs I've just reported in MyBB core. I like your ideas so far. Feel free to post any more that you have in the meantime. See you soon!

**Comment by lairdshaw** [comment]
@Eldenroot, here's what I've come up with so far. Can commit the changes on which this screenshot is based and send in a PR, otherwise am happy to hear how you think it can be improved.

![tyl-plugin-trophy-post-updated](https://user-images.githubusercontent.com/3241722/95497391-982a4580-09e5-11eb-9d87-59b287b9fb2a.png)

**Comment by lairdshaw** [comment]
@Eldenroot, I wasn't sure whether you were set on the second (last) image that you posted, but if so, then maybe one way to get my changes above to adhere to it better is to vertically extend the "Number of Thanks" data cell down two rows, and then centre it vertically as well as horizontally. Would that be better for you?

I also wasn't sure whether by their absence in that image of yours whether you'd intended for all headings/labels to be dropped, or whether you simply didn't take the time to add them in.

**Comment by Eldenroot** [comment]
@lairdshaw - I am sorry, I havent got any notification for your reply from GitHub!!!

Is possible to make the number of thx/likes bigger to use the whole right side? I know, there is a "forum name" but we can adjust it 👍 

![image](https://user-images.githubusercontent.com/778890/95623277-492bf100-0a75-11eb-9f69-ae6172a7f733.png)


Also is possible to apply new color settings for this thx/like counter in top liked/thxed post?

**Comment by lairdshaw** [comment]
How's this?

![tyl-plugin-trophy-post-updated 2](https://user-images.githubusercontent.com/3241722/95651337-0d546280-0b2d-11eb-85a1-15fe99ba7853.png)

**Comment by Eldenroot** [comment]
Great, really like this.

What about time/date format, doest it use mybb setting?

**Comment by lairdshaw** [comment]
Ah, good question. It was using the plugin's "Date/time format", but since that's specifically for the thanks/likes list, it is the wrong setting to use. I've changed it to use 'relative', which uses the MyBB setting either in the tooltip or when something like "Today" etc isn't applicable.

**Comment by Eldenroot** [comment]
Now I am happy :) thx!

What about thread prefix, is it a good idea to display it here?

**Comment by lairdshaw** [comment]
> What about thread prefix, is it a good idea to display it here?

Sure. Now implemented.

Anything else?

**Comment by Eldenroot** [comment]
I think we are done with this one :)
