### ISSUE TITLE
Incorporate Turkish language files

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#256]
As provided by Aytac [here](https://community.mybb.com/thread-169382-post-1357121.html#pid1357121).

@Eldenroot, as you are more experienced in dealing with MyBB and non-English languages, is this something you are willing to be assigned to?

**Comment by Eldenroot** [comment]
It depends, because maintaining of these languages is quite difficult (new lang phrases etc.)

I do not know how to easily do it. I caanot speak Turkish.

**Comment by lairdshaw** [comment]
Fair enough. I don't speak Turkish either. In that sense, we would either have to operate on trust or seek out a Turkish speaker to validate the translation.

And yes, maintenance is troublesome, but surely something is better than nothing? Doesn't MyBB fall back to the English translation anyway if there is no valid key for the language in question.

**Comment by Eldenroot** [comment]
I think there is no fall back. If the lang phrase is missing, the output is blank.

Can you please check?

**Comment by lairdshaw** [comment]
Confirmed: in the absence of a lang phrase, the output is blank; there is no fallback to English or any other language. However, I have at least run (most of) Aytec's language files through Google Translate, and they seem sane, so maybe we don't need another Turkish speaker to validate them.

**Comment by tuhafadam** [comment]
I am using the Turkish language file in my forum, it works fine:)

**Comment by lairdshaw** [comment]
I hope I'm not putting words in @Eldenroot's mouth, but I think he's concerned that if we officially support languages other than English, then every time we add new language strings, we have to ensure that they are added to the translated files too, and since we don't speak the languages, doing this properly would require us to contact all of the translators who originally translated those files, which is a tedious process not guaranteed to work (the translators might not be contactable or might no longer wish to work on the files).

For example, in the latest release, we added the following language entries to admin/config_thankyoulike.lang.php: `tyl_display_tyl_counter_search_page_title` and `tyl_display_tyl_counter_search_page_desc`, which aren't present in the supplied Turkish language files - so those Turkish language files, though just submitted, are _already_ out of date!

Here, then, are two possibilities:

1. We don't support non-English language files officially, but we welcome translators to create their own GitHub repositories of those files, to which we link from both README.md as well as our MyBB Extend page as unofficial resources. Then it is up to the translators, and not us plugin maintainers, to deal with user complaints about missing entries showing up blank.

2. We do officially support non-English language files, but with this caveat: when we add new language strings, we add English versions of those strings to the non-English language files with an (English) editing note that the new strings need translation, and when we update language strings, we add an (English) editing note to those strings in all of the non-English language files that they need re-translating, which is hopefully enough of a prompt for translators to supply those translations in PRs to the official repository.

Which do you guys prefer? Got any other ideas?

**Comment by tuhafadam** [comment]
When you share a new version, if you say the newly added language files, we will translate easier.

Tyl_display_tyl_counter_search_page_title and tyl_display_tyl_counter_search_page_desc language files are not visible in the latest version

**Comment by Eldenroot** [comment]
Hi @tuhafadam and thank you for your contribution.

We will think how to easily add translations into our plugin. There is a possibility to upload your translation into MyBB extend site directly, please try :) let us know.

https://community.mybb.com/mods.php?action=alltranslations&pid=360

@lairdshaw - what do you think?

**Comment by Eldenroot** [comment]
I have uploaded the Turkish translation to MyBB Extend site into our plugin page. Now it is waiting for the approval. If anything let me know, I expect that it will be approved in 3 days.
