### ISSUE TITLE
Provide unformatted versions of all numerical values for use in templates

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#265]
On the community forums thread, [tomjay78 asks](https://community.mybb.com/thread-169382-post-1357705.html#pid1357705):

> Is it possible to have "{$memprofile['tyl_unumrcvtyls']}" turned into a simple numerical value rather than a formatted one with <span> tags?
>
> For example, just like "{$post['tyl_unumrcvtyls']}" only spits out a number. I'm trying to use it in a conditional statement.

I think that this is a good idea, and I think we should generalise it so that all original numerical array entries like that are preserved, and formatted versions do not overwrite them but instead are included as new entries.

The only drawback I can see is that it may require changes to a fair few existing templates, but I haven't done a survey as yet to check.

**Comment by Eldenroot** [comment]
Wait, I do not get it.

We can use
`{$mybb->user['tyl_unumrcvtyls']}` not? It returns the numerical value.

**Comment by lairdshaw** [comment]
> We can use
> `{$mybb->user['tyl_unumrcvtyls']}` not? It returns the numerical value.

True, that's a good point. One (very minor?) problem though is that that value hasn't had any self-likes removed from it if the "Remove self-given thanks/likes from counters" setting is "Yes".

**Comment by Eldenroot** [comment]
Ok, agree, good point to add.

**Comment by lairdshaw** [comment]
Given your point, and the possibility that changes like this might break things for admins who are relying on the current behaviour of these variables in their templates, I'm closing this issue.

**Comment by lairdshaw** [comment]
@Eldenroot, I wasn't thinking clearly: when a profile is being viewed, the variable you suggest,  `$mybb->user['tyl_unumrcvtyls']`, represents the count of likes received by the member _viewing_ the profile, not the count of likes received by the member whose profile is being _viewed_ (which is the problematically-formatted variable), so it's not useful in this scenario after all. I'm reopening this issue.

**Comment by Eldenroot** [comment]
@lairdshaw - OK, no problem. We are here and we can discuss :)

So what do you suggest?

**Comment by lairdshaw** [comment]
@Eldenroot - Thanks. I'd suggest that we leave all values (like `tyl_unumrcvtyls`) that are pulled out of the database into arrays such as `$post` and `$memprofile` as-is, so that they can be used in template conditionals, and then create new entries (such as `tyl_unumrcvtyls_fmt`) into those arrays for the formatted variables that we _do_ end up displaying in the templates we provide.

This would require a few changes to the templates, which might cause some hassles to those who have modified those templates (they would need to run Find Updated Templates and merge the changes in), but that's the only drawback I can see.

What do you think? Is it worth it or is the drawback too significant given the perhaps only minor added value for users of the template conditional plugin?

**Comment by Eldenroot** [comment]
Just one question from my side (srry for that I am a little bit confused).

Please can you provide me an example of formatted nad not formatted variable? Will be there any performance impact? Because right now I use the {$mybb->user['tyl_unumrcvtyls']} variable for displaying the amount of thx/like for the logged user.

**Comment by lairdshaw** [comment]
> Please can you provide me an example of formatted nad not formatted variable?

Sure. I hope I'm not over-explaining or over-complicating things, but I'll try to explain an example clearly.

We use our `thankyoulike_memprofile()` function (in `inc/plugins/thankyoulike.php`) to hook in to MyBB core so we can add our `Total Likes Received` and `Total Likes Given` rows, plus our `Most Liked Post` box and (new) stats box to members' profiles. At the entry point to that hook-in function, on line 2526, the global variable `$memprofile` has had its value set (by core code) based on the row in the `mybb_users` table for the member whose profile is being viewed, which includes the value of one of the columns that our TYL plugin adds to that table, `tyl_unumrcvtyls`.

That is to say that on entry to that function, `$memprofile['tyl_unumrcvtyls']` is a plain integer reflecting the number of tyls received by the user whose profile is being viewed; it is "raw" from the database and has not (yet) been altered.

Then, at [line 2554](https://github.com/mybbgroup/Thank-you-like-system/blob/57dc96a29fe7c784fde613fb1dd77d4a1111591e/inc/plugins/thankyoulike.php#L2554) in that function, we call `tyl_check_remove_self_likes_from_post_array()` which passes `$memprofile` by reference and subtracts self-likes from the value of its `tyl_unumrcvtyls` entry if the relevant plugin's setting is "Yes". This is the first change made to `$memprofile['tyl_unumrcvtyls']` from its raw database value, but at least its value is still an integer.

More significantly, though, at [line 2630](https://github.com/mybbgroup/Thank-you-like-system/blob/57dc96a29fe7c784fde613fb1dd77d4a1111591e/inc/plugins/thankyoulike.php#L2630) in that function, we change the value of `$memprofile['tyl_unumrcvtyls']` from an integer to a formatted HTML string by calling `tyl_fmt_rcvd_likes_count()`.

By the time, then, that our member profile template, `thankyoulike_member_profile`, is rendered three lines later, the original, plain integer which is the number of likes received by the member whose profile is being viewed (either before or after having self-likes removed, if applicable) is no longer accessible at all to a designer wanting to use it conditionally in that template. All that is accessible (through `$memprofile['tyl_unumrcvtyls']`) is the HTML-formatted version of that number.

To give some more specific examples, assuming the member whose profile is being viewed has 1,100 likes, 100 of which are self-likes, and the setting to remove self-likes from counts is "Yes":

On entry to our `thankyoulike_memprofile()` function:
    `$memprofile['tyl_unumrcvtyls']` == `1100`
After line 2554 in that same function:
    `$memprofile['tyl_unumrcvtyls']` == `1000`
After line 2630 in that same function:
    `$memprofile['tyl_unumrcvtyls']` == `'<span class="tyl_rcvdlikesrange_1">1,000</span>'`

In any templates rendered after line 2630, then, a template designer has access to neither the original plain-integer value 1100 nor the revised value 1000, only to a string of HTML code which formats the revised value. Some of the more significant of those templates include: `thankyoulike_member_profile_box_content`, `thankyoulike_member_profile_box`, `thankyoulike_member_profile_like_stats`, and core's `member_profile`.

As is clear given tomjay78's question (even though he resolved his issue via the colourisation feature we recently added), there are conceivably situations where a template designer might _need_ access to that/those value(s), especially for use via a template conditional.

So, I'm proposing that we never alter `$memprofile['tyl_unumrcvtyls']`, so that template designers can always access the original 1100 integer value, and that we add a _new_ entry for the formatted version - perhaps `$memprofile['tyl_unumrcvtyls_fmt']`. Perhaps we could also add a new entry for the value _after_ self-likes have been subtracted (1000 in this example) - something like `$memprofile['tyl_unumrcvtyls_self_rem']`.

Then we would need to update those of our templates which use `$memprofile['tyl_unumrcvtyls']` to instead use `$memprofile['tyl_unumrcvtyls_fmt']`.

Does that make sense or is it all a bit eye-glazingly TL;DR?

**Comment by lairdshaw** [comment]
> Will be there any performance impact?

Nope.

**Comment by Eldenroot** [comment]
OK, deep great explanation. Thank you for that. Now I understand clearly. 

I support this idea, it could help make template and theme editing more feastable. 

We can add it into 3.3.8, I think there is no more issue left, so after that we can release a new version. So if you have some other ideas or improvements in your mind, let us know 👍 

Thank you buddy, have a great sunday!
