### ISSUE TITLE
Reuse of old alerts can make them hard to find

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#274]
Commit dc2741b adjusted alert behaviour such that when a tyl is added to a post, if that post already has an alert for it, then the alert is reused - it simply has its data updated appropriately given the new tyl.

This is fine when the existing alert is already unread. However, read alerts are also reused, and are switched back to unread. The problem with this is that the reused once-read alert is often so far back in the queue that it doesn't show up in the AJAX pop-up, with a bunch of other already-read alerts crowding it out.

A member of the board which I help to administer has complained about this, and I think it's a fair complaint. I was aware of this issue when committing the code, but I didn't realise the relative significance of the impact it would have.

My suggestion for resolving this issue is to only reuse unread alerts, and to otherwise generate new alerts.

Your thoughts?

**Comment by Eldenroot** [comment]
Yes, reuse only unread alerts + create a new alert instead of use "read alerts".
