### ISSUE TITLE
Alerts with multiple all-new tyls do not indicate that the tyls are new

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#275]
Since commit dc2741b, when an alert is created or updated for a post which has previously had a tyl alert for it viewed by the poster, the alert message indicates the number of new tyls since the previous alert was viewed.

However, when an alert is created or updated for a post which has not previously had a tyl alert for it viewed by the poster, the alert message does not indicate the number of new tyls (which is all of them). This is fine when there is only a single tyl, but uninformative when there are more than one.

My suggestion for resolving this issue is to simply add in that missing information to the alert message in that situation.

Your thoughts?

**Comment by Eldenroot** [comment]
I agree, feel free to fix it. Thank you!
