### ISSUE TITLE
Use separate lang string for thanks and for likes

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#277]
![image](https://user-images.githubusercontent.com/778890/100283247-6f4a1980-2f6d-11eb-90f7-0791b0ca0f25.png)
![image](https://user-images.githubusercontent.com/778890/100283273-7bce7200-2f6d-11eb-9e94-44e4a86061f0.png)

We need to use separate lang string for stats in member profile, this lang string will be used based on the settings in ACP (use thanks OR like system) as we already done in other parts of this plugin,

This will make life much easier for some admins and translators

**Comment by Eldenroot** [comment]
Two more, maybe there will be more... I have overlooked this, sry.

![image](https://user-images.githubusercontent.com/778890/100284594-b0432d80-2f6f-11eb-9be4-9c5ca6fcbea0.png)

**Comment by lairdshaw** [comment]
Oh, separate language strings already _are_ used - the ones you see with "tyl" in the middle are simply placeholders: the plugin replaces them dynamically with the ones with "likes" or "thanks" in the middle, depending, as you suggest, on whether thanks or likes are set in the ACP. See here:

https://github.com/mybbgroup/Thank-you-like-system/blob/a305cf3b92bc0557ba28bc4ef940bbf61eee982b/inc/plugins/thankyoulike.php#L2782-L2801

Arguably, we should (if it doesn't cause an error) simply remove those placeholders from the language file, or (which definitely won't cause an error) simply set them to an empty string to save translators the unnecessary effort of translating them.

**Comment by Eldenroot** [comment]
Why not to use {1} in lang file as we do for others?

**Comment by lairdshaw** [comment]
Because I thought I saw it done this way in a few other places in the plugin, and the idea took hold in me. Using {1} could be better though - fewer entries in the language file.
