### ISSUE TITLE
Do not use mybb lang for time periods in member profile - stats page

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#278]
We should really avoid using mybb core lang strings for time periods... we should add all of used periods in our language file.

Now we use only these 2, we should add all of them

![image](https://user-images.githubusercontent.com/778890/100283526-fc8d6e00-2f6d-11eb-88a5-8c8e6cf3d082.png)

**Comment by lairdshaw** [comment]
OK. I've got no problem with that - happy for you to add them.

**Comment by Eldenroot** [comment]
Thank you buddy. We will be fully independent... so we will not have to check every lang changes in every MyBB release.

**Comment by Eldenroot** [comment]
@lairdshaw - this will be the last issue for 3.3.9 release, please can you send a PR? I would like to target a release for this weekend. 

Or is there anything else what should be changed/improved/fixed? We do not have to rush... thank you!

**Comment by lairdshaw** [comment]
> please can you send a PR?

Done.

> is there anything else what should be changed/improved/fixed?

A few minor things, yes - see PR #286.
