### ISSUE TITLE
Mistake in a lang string

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#279]
![image](https://user-images.githubusercontent.com/778890/100284713-e7b1da00-2f6f-11eb-99e8-96048b498019.png)

It should be probably only thanked, not thanked/liked.

**Comment by lairdshaw** [comment]
Ah, that's simply another placeholder string as per [my comment](https://github.com/mybbgroup/Thank-you-like-system/issues/277#issuecomment-733960847) in #277.

**Comment by lairdshaw** [comment]
Resolved by #285.
