### ISSUE TITLE
Make default color for ajax jgrowl popup windows

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#280]
Right now we use MyBB style based... I think we can use one style for all thankyoulike plugin notifications to override the mybb setttings.

.jGrowl .jGrowl-notification.jgrowl_success,
.jGrowl .jGrowl-notification.jgrowl_error{
    background: black !important;
    border: 1px solid black !important;
    color: #fff !important;
}

**Comment by lairdshaw** [comment]
Sure, why not? Totally happy for you to add that styling.

**Comment by Eldenroot** [comment]
OK, please feel free to merge any PR :) I will not be there tommorow.

**Comment by lairdshaw** [comment]
Here's a PR, but I won't merge it for now - best to have you test it out first and see if it does what you wanted.
