### ISSUE TITLE
Template changes in member_profile template are not added properly

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#290]
I think that there is a small issue (at least on my board) - this is not added on install

https://github.com/mybbgroup/Thank-you-like-system/blob/master/inc/plugins/thankyoulike.php#L1298

Please, could you check this before 3.3.9 release?

**Comment by lairdshaw** [comment]
Can't replicate this on my local dev board, seems to work fine here. Has your `member_profile` template been customised in any way already? Is there any reason the regex `'#{\$reputation}(\r?)\n#` would fail to match anything in that template on your board?

**Comment by Eldenroot** [comment]
Hmm, let it be... I have modified it. I will close this up and open eventually when I get more info.

**Comment by lairdshaw** [comment]
OK. Perhaps the problem is that in that template, `{$reputation}` is not immediately followed by a line break?

**Comment by lairdshaw** [comment]
On your board, I mean.
