### ISSUE TITLE
Settings mismatch

### ISSUE THREAD

**Issue by schauan** [mybbgroup/Thank-you-like-system#292]
I had used rel. 2.1.0, on mybb 1.8.21 and php 7.3
Today I installed Update 1.8.24. Before, I had deactivated all plugins manually. After Update I want to actualise tyl.  I had deinstalled te plugin - with ... "no" to keep datas.  Then I had installed the new version. The installation takes a few minutes, about 3 to  4.... It was very long. 
Then I want to see the plugin and settings. As first I saw 4 symbols, the first and the last without description.
Then I choose settings. There ara alo many options an Buttons without description  ...

![SymbolsWithoutDescription](https://user-images.githubusercontent.com/29002036/101916234-f1ba1680-3bc6-11eb-9da6-a75a7aa6adea.png)
![Options+ButtonsWithoutDescription](https://user-images.githubusercontent.com/29002036/101916384-27f79600-3bc7-11eb-9f58-f51eb53f0db7.png)
 
So I can't use this version. Has anyone an idea what there was happen and what I can do tho fix it?

**Comment by Eldenroot** [comment]
Use the default english acp language pack... german is not compatible with the latest version (not official translation).

Go to your language folder, acp and delete tyl related files.

**Comment by schauan** [comment]
Fine, it works :-) 
The first issue immediately after swap the language files and refresh the site.
The second issue after reinstalling the plugin.  
Thank you very much for your help, have a good xmas-time :-)
