### ISSUE TITLE
The creation of the new indexes might time out

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#295]
The indexes on the `thankyoulike` table added in commit 57dc96a (`uid_dateline`, `puid_dateline`, `puid_uid`, and `puid_pid`) are created on auto-upgrade when reactivating the plugin, however, if that table has a lot of rows, then the creation of these indexes might take so long that the web server or database connection times out and it ends up that one or more of them are not created.

In case this happens, the existence of the indexes should be checked for on the ACP plugins page, and if any of them do not exist, admins should be notified and given an opportunity to create each of them with a single click.

**Comment by Eldenroot** [comment]
Good catch!

**Comment by lairdshaw** [comment]
I think that our solution to this problem - PR #296, which supports semi-automated creation of the indexes via the plugin's ACP listing - is not enough: really, we should totally remove the auto-creation of the indexes on plugin auto-upgrade, and rely on users semi-automatically creating them per the feature introduced by that PR.

I say this because if/when the index creation times out on plugin auto-upgrade, the upgrade process will not have completed, and the admin might not know to repeat it by deactivating and then reactivating the plugin after manually creating the indexes. We know that this scenario occurs in practice given schauan's experience in the MyBB Community Forums thread [Thank You Like System Update Errors](https://community.mybb.com/thread-230693.html).

What do you guys think?

**Comment by Eldenroot** [comment]
I agree with you, not everyone follow our instructions in changelog...

So we should keep bombarding the admin (with some notification bar in ACP which will be displayed until user click on "run index creation process) or make it bullet proof...
