### ISSUE TITLE
Need to bump minimum required MyAlerts version to 2.0.4

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#297]
This is the latest version of MyAlerts, and it is required because it is the version in which a hook upon which we depend, `myalerts_alert_manager_mark_read`, is introduced. For earlier versions of MyAlerts (without this hook), all tyl alerts will count as "new" all tyls for a post, rather than only those tyls which have been added since the last time an alert for that post was viewed (because the `tyl_last_alerted_tyl_id` column of the `posts` table will never be updated, since it is updated when we hook in to `myalerts_alert_manager_mark_read`).

There's no need to fix anything in the code - I'm simply raising this issue so that @Eldenroot knows to add the new minimum MyAlerts version to documentation / release notes / etc as necessary.

**Comment by Eldenroot** [comment]
Hmm, I will mention in the patch notes... anyway is there any possibility to check for MyAlerts version and notice the use (in ACP) to upgrade MyAlerts to make it working correctly?

**Comment by lairdshaw** [comment]
Sure, we could do that. If you like, I'll add that check+warning soon, so that it can be included in the imminent release of 3.4.0.

**Comment by lairdshaw** [comment]
PR #299 adds that check+warning.

**Comment by Eldenroot** [comment]
Fixed by #299
