### ISSUE TITLE
Restructure the plugin's files

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#309]
Suggested restructuring:

Create a new top-level `upload` directory and move into it the `images`, `inc`, and `jscripts` directories, and the `thankyoulike.php` and `tylsearch.php` files.

Create a new top-level `scripts` directory and move into it the `converter.php` script. We would add martec's additional conversion script of #308 to this directory. Add a README.md to this directory to explain what the scripts are for.

Update the top-level README.md to be compatible with the new structure.

**Comment by Eldenroot** [comment]
Ok, good suggestion
