### ISSUE TITLE
Refactor, update, test, and rename the converter.php script

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#310]
1. Refactor so as to eliminate redundant code.
2. Update so as to ensure that the conversion works for current versions of the plugins from which to migrate.
3. Test each of the supported plugins to ensure that the updated code works correctly.

I have already done all of this, and will soon submit a PR.

**Comment by Eldenroot** [comment]
Thank you @lairdshaw
