### ISSUE TITLE
[Question] Upgrade from 2.1 to 3.4

### ISSUE THREAD

**Issue by igormaozao** [mybbgroup/Thank-you-like-system#316]
Hi, I just realized I never upgrade the plugin in my forum.

I've read the upgrade readme, but I got confused about the MyAlerts plugin, which **I DON'T** use, so can I just follow the upgrade steps (deactivate, upload the new files, reactivate) normally?

By the way, in the upload folder, should I upload the plugin files in there, or can I upload the "Thank-you-like-system-3.4.2" folder?

Thanks

**Comment by lairdshaw** [comment]
Yes, you can just follow the upgrade steps. No need to worry about MyAlerts.

The version of the plugin with the `upload` folder has not yet been officially released, and is only available from GitHub, so if you download the latest release, 3.4.2, then you need to upload the files from the top-level folder, yes.
