### ISSUE TITLE
Freezing when I give a like out

### ISSUE THREAD

**Issue by Cardoso1900G** [mybbgroup/Thank-you-like-system#317]
Hi, I was just starting to configure my forum and when using your plugin i noticed that every time i give a like to a thread the page just freezes and the like doesn't get delivered.

Here, if you make an account and try to like you'll see what i mean:

http://cardgg.epizy.com/

**Comment by lairdshaw** [comment]
Solved in Discord chat. The problem seems to have been that the `thankyoulike.php` file was missing from the board's root directory.
