### ISSUE TITLE
Problems after upgrading to PHP 8

### ISSUE THREAD

**Issue by Tarekma7** [mybbgroup/Thank-you-like-system#324]
Hi

The plugin is working perfect on PHP 7.4

Upgrading to PHP 8 results in the following issues and warnings

Warning [2] Undefined variable $unapproved_shade - Line: 2 - File: inc/plugins/thankyoulike.php(2151) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2151) : eval()'d code	2	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2151	eval
/inc/plugins/thankyoulike.php	2206	tyl_build_post_likers_display
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined variable $tyl_expcol - Line: 3 - File: inc/plugins/thankyoulike.php(2216) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2216) : eval()'d code	3	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2216	eval
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined variable $tyl_title_display - Line: 4 - File: inc/plugins/thankyoulike.php(2216) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2216) : eval()'d code	4	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2216	eval
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined variable $tyl_title_display_collapsed - Line: 4 - File: inc/plugins/thankyoulike.php(2216) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2216) : eval()'d code	4	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2216	eval
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined variable $tyl_data_display - Line: 5 - File: inc/plugins/thankyoulike.php(2216) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2216) : eval()'d code	5	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2216	eval
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined array key "thankyoulike" - Line: 5 - File: inc/plugins/thankyoulike.php(2216) : eval()'d code PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php(2216) : eval()'d code	5	errorHandler->error_callback
/inc/plugins/thankyoulike.php	2216	eval
/inc/class_plugins.php	142	thankyoulike_postbit
/inc/functions_post.php	885	pluginSystem->run_hooks
/showthread.php	1118	build_postbit

Warning [2] Undefined array key "gid" - Line: 3389 - File: inc/plugins/thankyoulike.php PHP 8.0.23 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/thankyoulike.php	3389	errorHandler->error_callback
/inc/class_plugins.php	142	thankyoulike_settings_page
/admin/modules/config/settings.php	873	pluginSystem->run_hooks
/admin/index.php	825	require

Please fix and update

**Comment by Eldenroot** [comment]
Thank you for reporting this! If anything else, please let us know.

Will be fixed in one of the future releases... :)

@laird - it seems to be one same issue in many instances

**Comment by lairdshaw** [comment]
Am about to be away from my dev setup for a few days, and don't have time to fix this before then, so please be patient - if anyone else wants to fix this in the meantime, then please go ahead.

**Comment by SvePu** [comment]
Maybe someone could test the fixes please => https://github.com/mybbgroup/Thank-you-like-system/commit/4b72cdb75ee2bf0df031982e8a7d8a0ac04404ed

**Comment by Eldenroot** [comment]
Hi, unfortunately I do not use php 8.x yet. I am waiting for my webhosting.

**Comment by Eldenroot** [comment]
@SvePu - on my testing board with php 8.0 looks fine. Do you use php 8.0 or newer to confirm? Thx

**Comment by SvePu** [comment]
@Eldenroot my test board runs with PHP 8.1.13.

![mybb_testboard](https://user-images.githubusercontent.com/9826631/210143519-5b555c67-6a36-441a-b784-67ea4fbaa1f2.png)

**Comment by Eldenroot** [comment]
Cool, I am closing this issue. If anything we can open a new one. Thank you
