### ISSUE TITLE
how to add total like threads in forumdisplay_thread template?

### ISSUE THREAD

**Issue by Mediuz** [mybbgroup/Thank-you-like-system#325]
hi, i want display total like thread in forum display. how to display total like in template forumdisplay_thread? i try use this {$post['thankyoulike']} but not work.
![Screenshot_1](https://user-images.githubusercontent.com/121945612/210552659-b0007b0e-36dc-49a9-aa39-2ad841c5f942.png)

**Comment by Eldenroot** [comment]
Hi, you should be able to use exsting code from TYL system plugin. Anyway we cannot support custom themes.
