### ISSUE TITLE
Add the `tyl_tnumtyls` column back in

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/Thank-you-like-system#327]
This column, caching in the threads table the total likes count for all posts in the thread, was removed in commit 226df2f at my suggestion in issue #194 "Do we need the tyl_tnumtyls column in the threads table?"

I suggested this because the column wasn't used in the plugin other than to provide a very minor efficiency improvement, and it seemed pointless to me.

I now think that this was a mistake, because I later became aware of at least one plugin that used the column, and we sometimes have users wanting access in templates to a count of likes in a thread, such as in last week's issue  #325, "how to add total like threads in forumdisplay_thread template?"

I now suggest that we revert that commit and add code to reinitialise the column.

I'll shortly supply a PR that does this. In the meantime, please feel free to comment on this suggestion.

**Comment by Eldenroot** [comment]
OK, no problem. We can release a bug fix release (actually it is not a bug, but it will be a minor release...) otherwise we can bundle some more fixes if there will be some space.

Thank you!
