### ISSUE TITLE
MyBB SQL Error

### ISSUE THREAD

**Issue by ookris** [mybbgroup/Thank-you-like-system#352]
When I try to activate the plugin, I get this error:
`MyBB has experienced an internal SQL error and cannot continue.`

My server:
MyBB: 1.8.38
PHP 8.1.29
Database: PostgreSQL 16.3

**Comment by lairdshaw** [comment]
That's because, unfortunately, PostgreSQL isn't currently supported by this plugin.

**Comment by lairdshaw** [comment]
No worries. Closing this issue.
